# Generated by Django 3.1.3 on 2021-04-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='paid',
            new_name='ordered',
        ),
    ]
